In [1]:
import numpy as np

In [5]:
a = np.array([5,5,5,5])
a
a.dtype

dtype('int32')

In [6]:
type(a)

numpy.ndarray

In [7]:
len(a)

4

In [8]:
b = np.zeros(2)
b

array([0., 0.])

In [9]:
d = np.empty(3)
d

array([9.90381088e-312, 0.00000000e+000, 4.94065646e-324])

In [10]:
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [11]:
f = np.arange(1,20)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
f = np.arange(1,20,2)
f

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
h = np.linspace(0,10,num=5)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
i = np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [15]:
j = np.ones(3,dtype=np.float64)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [16]:
c= np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])