Getting started with the Tensorflow

In [1]:
import tensorflow as tf

In [3]:
string1 = tf.Variable("this is string",tf.string)
string1

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is string'>

In [11]:
number = tf.Variable(23,tf.int16)
print(number)
print(number.shape)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>
()


In [10]:
floating = tf.Variable(34.3,tf.float64)
floating

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=34.3>

Rank and Degree in tensor

In [13]:
rank1_ensor = tf.Variable(["cui","wah"],tf.string)
rank1_ensor

<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'cui', b'wah'], dtype=object)>

In [20]:
rank2_tensor = tf.Variable([['cui','wah'],['sem','eight']],tf.string)
rank2_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'cui', b'wah'],
       [b'sem', b'eight']], dtype=object)>

To determine the rank of the tensor we can find the following commands

In [21]:
tf.rank(rank1_ensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [22]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Checking the shape of the tensor

In [23]:
rank1_ensor.shape


TensorShape([2])

In [24]:
rank2_tensor.shape

TensorShape([2, 2])

changing the shape

In [32]:
tensor1 = tf.ones([3,4,5])
tensor2 = tf.reshape(tensor1,[6,10,1])
tensor3 = tf.reshape(tensor2,[5,-1])

In [33]:
print("tensor1 :",tensor1)
print("tensor2 is:",tensor2)
print("tensor3 is:",tensor3)

tensor1 : tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 4, 5), dtype=float32)
tensor2 is: tf.Tensor(
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]], shape=(6, 10, 1), dtype=float32)
tensor3 is: tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], sha

Types of Tensor
. variable
. Constant
. Paceholder
. SparseTensor

In [34]:
#evaluating tensor

with tf.Session() as sess:
    tf.eval()

AttributeError: module 'tensorflow' has no attribute 'Session'