In [1]:
import numpy as np
price = np.array([20,3,1,3,2])
price

array([20,  3,  1,  3,  2])

In [2]:
price.mean()

5.8

In [5]:
# for a specific interval
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [6]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [7]:
np.ones(5,dtype=np.float64)

array([1., 1., 1., 1., 1.])

Array Function

In [11]:
a =np.array([12,23,23,112,45,23,67,34,2,5,888])
a

array([ 12,  23,  23, 112,  45,  23,  67,  34,   2,   5, 888])

In [13]:
a.sort()
a

array([  2,   5,  12,  23,  23,  23,  34,  45,  67, 112, 888])

In [21]:
b = np.array([10,4,23,23,23,35,56,7])


In [26]:
c = np.concatenate((a,b))
c
c.sort()
c


array([  2,   4,   5,   7,  10,  12,  23,  23,  23,  23,  23,  23,  34,
        35,  45,  56,  67, 112, 888])

2-D array


In [29]:
ab = np.array([[1,2,3,4],[6,7,9,10]])
ab

array([[ 1,  2,  3,  4],
       [ 6,  7,  9, 10]])

In [30]:
b = np.array([[12,23,43,54],[344,34,22,4]])
b

array([[ 12,  23,  43,  54],
       [344,  34,  22,   4]])

In [39]:
c = np.concatenate((ab,b),axis=1)
c.sort()
c

array([[  1,   2,   3,   4,  12,  23,  43,  54],
       [  4,   6,   7,   9,  10,  22,  34, 344]])

In [40]:
c.ndim


2

In [42]:
c.size

16

In [43]:
c.shape

(2, 8)

In [47]:
d = c.reshape(4,4)
d

array([[  1,   2,   3,   4],
       [ 12,  23,  43,  54],
       [  4,   6,   7,   9],
       [ 10,  22,  34, 344]])

In [49]:
# reshape
np.reshape(a,newshape=(1,11),order='C')

array([[  2,   5,  12,  23,  23,  23,  34,  45,  67, 112, 888]])

In [51]:
#converting 1-d to 2-d

x = np.array([1,2,3,4,5])
x.shape

(5,)

In [53]:
b

array([[1, 2, 3, 4, 5]])

In [54]:
b.shape

(1, 5)

In [55]:
#column wise
b = x[:,np.newaxis]

In [56]:
b

array([[1],
       [2],
       [3],
       [4],
       [5]])